name: vehicle_web
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
   
   

  cupertino_icons: ^1.0.8
  firebase_core: ^4.12.1
  firebase_database: ^12.4.6
  firebase_auth: ^6.5.6
  google_maps_flutter_web: ^0.6.2+3
  google_maps_flutter: ^2.17.1
  cloud_firestore: ^6.7.1
  intl: any  
dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/fleet_icon.png
    - assets/images/history_start.png
    - assets/images/history_end.png
    - assets/images/playback_vehicle.png 
    - assets/images/history_point.png
    - assets/images/vehicle_marker.png
    - assets/images/vehicle_marker_selected.png